exp:
  name: "Digits_DER"
  savedir: "./logs"
  tensorboard_dir: "./tensorboard"
  debug: False


#Model Cfg
model: "incmodel"
convnet: 'resnet18' #modified_resnet32, resnet18
train_head: 'softmax'
infer_head: 'softmax'
channel: 64
use_bias: False
last_relu: False

der: True
use_aux_cls: True
aux_n+1: True
distillation: "none"
temperature: 2

reuse_oldfc: False
weight_normalization: False
val_per_n_epoch: -1 # Validation Per N epoch. -1 means the function is off.
save_ckpt: True
save_mem: True
load_mem: False


#Optimization;Training related
task_max: 5  # Split 10 digits into 5 tasks of 2 digits each
lr_min: 0.00005
lr: 0.01  # Lower learning rate for simpler dataset
weight_decay: 0.0005
dynamic_weight_decay: False
scheduler: 'multistep'
scheduling:
  - 30  # Reduced epochs for smaller dataset
  - 45
lr_decay: 0.1
optimizer: "sgd"
epochs: 50  # Reduced epochs for smaller dataset
resampling: False
warmup: True
warmup_epochs: 5

postprocessor:
  enable: False
  type: 'bic' #'bic', 'wa'
  epochs: 1
  batch_size: 50  # Smaller batch size for the smaller dataset
  lr: 0.1
  scheduling:
    - 20
    - 30
    - 40
  lr_decay_factor: 0.1
  weight_decay: 0.0005

decouple:
  enable: True
  epochs: 15
  fullset: False
  lr: 0.01  # Lower learning rate
  scheduling:
    - 7  # Adjusted schedule for fewer epochs
  lr_decay: 0.1
  weight_decay: 0.0005
  temperature: 2.0

pretrain:
  epochs: 50  # Reduced epochs for smaller dataset
  lr: 0.01
  scheduling:
    - 20
    - 35
    - 45
  lr_decay: 0.1
  weight_decay: 0.0005


# Dataset Cfg
dataset: "digits"  # New dataset type
trial: 0
increment: 2  # 2 classes per task for 10 digits
batch_size: 50  # Smaller batch size for simpler dataset
workers: 4  # Fewer workers due to smaller dataset
validation: 0.5  # 50% validation split
random_classes: False
start_class: 0  # Start with the first 2 digits (0, 1)
start_task: 0
max_task: 5  # 5 tasks total (0-1, 2-3, 4-5, 6-7, 8-9)

#Memory
coreset_strategy: "random"  # Strategy for selecting exemplars
mem_size_mode: "uniform_fixed_total_mem"
# memory_size: 70  # Smaller memory size for digits dataset
memory_size: 0  # Smaller memory size for digits dataset
fixed_memory_per_cls: 7  # Keep 20 examples per digit
# fixed_memory_per_cls: 0  # Keep 20 examples per digit

# Misc
device: 0  # GPU index to use, for cpu use -1
seed: 1993