exp:
  name: "Iris_DER"
  savedir: "./logs"
  tensorboard_dir: "./tensorboard"
  debug: False

# Model Cfg
model: "incmodel"
convnet: 'resnet18'
train_head: 'softmax'
infer_head: 'softmax'
in_channels: 4 
use_bias: False
last_relu: False

der: True
use_aux_cls: True
aux_n+1: True
distillation: "none"
temperature: 2

reuse_oldfc: False
weight_normalization: False
val_per_n_epoch: -1 # Validation Per N epoch. -1 means disabled.
save_ckpt: False
save_mem: False
load_mem: False

# Optimization; Training related
task_max: 3  # 3 classes into 3 tasks
lr_min: 0.00005
lr: 0.01
weight_decay: 0.0005
dynamic_weight_decay: False
scheduler: 'multistep'
scheduling:
  - 10
  - 20
lr_decay: 0.1
optimizer: "sgd"
epochs: 30
resampling: False
warmup: False
warmup_epochs: 5

postprocessor:
  enable: False
  type: 'bic'
  epochs: 1
  batch_size: 16
  lr: 0.1
  scheduling:
    - 5
    - 10
  lr_decay_factor: 0.1
  weight_decay: 0.0005

decouple:
  enable: False
  epochs: 0
  fullset: False
  lr: 0.0
  scheduling: []
  lr_decay: 0.0
  weight_decay: 0.0
  temperature: 2.0

pretrain:
  epochs: 0
  lr: 0.0
  scheduling: []
  lr_decay: 0.0
  weight_decay: 0.0

# Dataset Cfg
dataset: "iris"
trial: 0
increment: 1  # one class per task
batch_size: 4
workers: 0
validation: 0.75  # 75% validation split
random_classes: False
start_class: 0
start_task: 0
max_task: 3  # three tasks total (0, 1, 2)

# Memory
coreset_strategy: "random"
mem_size_mode: "uniform_fixed_total_mem"
memory_size: 0  # No replay memory
fixed_memory_per_cls: 0

# Misc
device: 0 # GPU
seed: 1993
